services:
  pv2mqtt:
    build:
      context: .
      dockerfile: Dockerfile.notls
    container_name: pv2mqtt
    restart: unless-stopped
    env_file:
      - .env
    # Host networking is required for mDNS hub discovery
    network_mode: host
